# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://dss.ncf.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /specialformats
# CONTENTdm server url
sobek-url: http://ncf.sobek.ufl.edu/special
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: NCF Special Formats
# header and head metadata
tagline: NCF Specials Formats
description: "NCF Specials Formats" 
# Organization branding
organization-name: "DSS"
organization-link: https://dss.ncf.edu
organization-logo-banner: https://3rft043w17da3uqixj33lfj7-wpengine.netdna-ssl.com/library/wp-content/plugins/ncfgears-library/images	/jblogo.png
organization-logo-nav: https://3rft043w17da3uqixj33lfj7-wpengine.netdna-ssl.com/library/wp-content/themes/newcollege2016/img/logo-footer-white.png

# Collection settings
# contentdm collection name 
sobek-collection-id: special
# name of metadata file, be sure to also change page_gen data setting!
metadata: output
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'output'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
